### ISSUE TITLE
does not work 

### ISSUE THREAD

**Issue by aliafshany** [BlueGreenMagick/anki-misc-addons#3]
hi there
i'd like to ask for your help
this add-n doesn't work for me on 2.1.52 and neither on 2.1.49

please give me a hand if you can.
best

![image](https://user-images.githubusercontent.com/40741745/168321387-6a0546e0-a345-4c80-9d04-a5f99e4463b7.png)

**Comment by BlueGreenMagick** [comment]
Apparently, you can't put white space between shortcut keys. 

So change the shortcut to `"CTRL+SHIFT+1"` and `"CTRL+SHIFT+2"` and it should work
